### PR TITLE
Created devsuite.project

### PR DESCRIPTION
**Pull request by Dantheman720**
Devsuite.project will allow us to normalize projects for RHD.

### CODE REVIEW

**Comment by Dantheman720** [comment]
@unibrew - I'm not sure whether or not the jbossorg_sbs field needs to be populated with anything special. I noticed that you recently pushed the CDK project file. Is there a way that I can find out what needs to go in that field?

**Comment by unibrew** [comment]
I assume it's some kind of upcoming project, right ? The variable should contain ID number of Jive(formerly named SBS) space for this project but I don't see anything related to this project here https://developer.jboss.org/welcome Possibly not yet created or not meant to be here, no clue.

**Comment by Dantheman720** [comment]
Yeah, I don't think they were planning on having a forum for this since it's just a compilation of different tools.

@paulrobinson ^^ Including in case I am misspeaking.

**Comment by paulrobinson** [comment]
Agreed

**Comment by unibrew** [comment]
I cherry-picked the commit to master and v2.1.5 branches and also pushed the new project to our staging and production DCP2 instances.

**Pull request closed without merging**
