### PR TITLE
DEVELOPER-2870 - Updated resources query to be able to filter blogposts by sys_url_view

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by unibrew** [comment]
I pushed it to our staging DCP. Let me know if everything works as expected and I'll push it to prod.

**Comment by Dantheman720** [comment]
Awesome! Thanks! I'll get a PR up for the JS change and let you know.

**Comment by unibrew** [comment]
cherry-picked to master and v2.1.5 branches and pushed to production.
Thanks!

**Comment by Dantheman720** [comment]
Thanks Rysiek!

**Pull request closed without merging**
