### PR TITLE
DEVELOPER-3846 - Added configurations for RHD Drupal Cheatsheets

### PR DESCRIPTION
**Pull request by Dantheman720**

### CODE REVIEW

**Comment by Dantheman720** [comment]
@unibrew - Wanted to followup and see if I needed to make any changes here.

**Comment by unibrew** [comment]
We've just took a look with Libor on this configuration and it seems mostly correct. If you could only add mapping for download_url (probably identical as sys_url_view has atm) and also the value that you put in field named "id" would be a better fit for "sys_content_id" which you're currently missing.
Lastly, I wasn't able to find REST endpoint under which drupal is serving this cheatsheet data so if you could share it with us.

**Comment by Dantheman720** [comment]
@unibrew - I'm not sure what was meant by "_If you could only add mapping for download_url (probably identical as sys_url_view has atm)_". I added mapping for it, but I don't understand the relation between that and sys_url_view.

**Comment by unibrew** [comment]
Don't worry about it. I'll release this on Monday morning as I'm travelling today. Thanks for sending out the drupal URLs as well.

**Pull request merged**
