### PR TITLE
Create initial configuration files by RHD website indexer. Closes #31

### LINKED ISSUE #31: Create configurations to index content from RHD sitemap
See http://developers.redhat.com/sitemap.xml
Related: https://issues.jboss.org/browse/RHD-981

### PR DESCRIPTION
**Pull request by unibrew**

### CODE REVIEW

**Comment by lkrzyzanek** [comment]
I think it looks good. I'm not expert on rivers but those mappings seems good to me.

**Comment by lukas-vlcek** [comment]
@unibrew just note I added `master` label. This might sound like nitpicking but in some cases it can really happen that the change goes only to specific branch and not to the master. This is why I created this label for (to distinguish such cases).

**Comment by unibrew** [comment]
@lukas-vlcek aye, aye :)
I cherry-picked the commit to master and v2.1.2.

Thank you for the contribution :)

**Comment by unibrew** [comment]
oh and the river is running fine in production

**Pull request closed without merging**
