### PR TITLE
[query] Remove escaping in resources query template (both doc and jso…

### LINKED ISSUE #55: [query] Remove escaping in resources query template (both doc and json)
#### Remove escaping in `resources.md` documentation

Replace

```
{\"term\":{\"sys_project\":\"{{.}}\"}},
```

with

```
{ "term" : { "sys_project" : "{{.}}" }},
```
#### Remove escaping in `resources.json` query

Replace

```
{\\\"term\\\":{\\\"sys_project\\\":\\\"{{.}}\\\"}},
```

with

```
{\"term\":{\"sys_project\":\"{{.}}\"}},
```

### PR DESCRIPTION
**Pull request by lukas-vlcek**
…n). Closes #55

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
Should be ported to branches `master`, `v2.1.4` and `v2.1.5`.
Delete branch `55` after merge.

**Comment by lukas-vlcek** [comment]
**NOTE:** This PR includes change to query json file which means it requires push to relevant live DCP instances. //cc @unibrew

**Comment by unibrew** [comment]
I pushed this to prod

**Comment by unibrew** [comment]
and staging DCP2

**Pull request merged**
